### ISSUE TITLE
CCA: testing for Bugzilla 5.0

### ISSUE THREAD

**Issue by okc-ok** [ravanelli/mirror_test#12]
<cde:info> Mirrored with LTC bug https://bugzilla-test.linux.ibm.com/show_bug.cgi?id=181899 </cde:info>

This issue should not mirror immediately.

**Comment by cdeadmin** [comment]
Setting the mirror label to enable mirroring.

**Comment by cdeadmin** [comment]
Testing comment from LTC to GitHub.

**Comment by okc-ok** [comment]
Closing the test issue.

**Comment by okc-ok** [comment]
Comment for testing the investigator.

**Comment by cdeadmin** [comment]
Rejecting test bug ... will not fix.

**Comment by okc-ok** [comment]
Thanks for the test!
