### ISSUE TITLE
Mirror test from GHE to LTC

### ISSUE THREAD

**Issue by okc-ok** [ravanelli/mirror_test#13]
<cde:info> Mirrored with LTC bug https://bugzilla-test.linux.ibm.com/show_bug.cgi?id=181901 </cde:info>

Testing before the weather turns!

**Comment by cdeadmin** [comment]
Approving this issue for mirroring.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2019-11-26 16:26:18 EDT-------
Moving the test bug to WORKING.

**Comment by okc-ok** [comment]
Closing the test GHE issue. Check the status changes in the test bug.

**Comment by cdeadmin** [comment]
Confirm whether cdeadmin can state-change this bug.

**Comment by okc-ok** [comment]
Test closing again.

**Comment by okc-ok** [comment]
Test closing again after updating the XMLDoggierFieldMapping class

**Comment by okc-ok** [comment]
Test reopening the GHE issue.

**Comment by okc-ok** [comment]
... and reclose again!

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2019-11-26 16:52:08 EDT-------
Successful test!
