### ISSUE TITLE
Github Bridge - Testing reverse mirror 

### ISSUE THREAD

**Issue by ravanelli** [ravanelli/mirror_test#3]
# **Github Bridge - Testing reverse mirror** 

`Testing `
_**### Github Bridge - Testing reverse mirror**_ 

<cde:info> Mirrored with LTC bug #147850 </cde:info>

**Comment by cdeadmin** [comment]
# **Github Bridge - Testing reverse mirror** 

`Testing `
_**### Github Bridge - Testing reverse mirror**_

**Comment by ravanelli** [comment]
#6 
Reference test[https://assets-cdn.github.com/images/modules/open_graph/github-mark.png](url)

**Comment by ravanelli** [comment]
![image](https://user-images.githubusercontent.com/6576497/28433946-01a5605c-6d64-11e7-895c-2e4be5225029.png)

**Comment by cdeadmin** [comment]
------- Comment (attachment only) From rmatos@br.ibm.com 2017-07-20 15:05:58 EDT-------

**Comment by cdeadmin** [comment]
------- Comment From rmatos@br.ibm.com 2017-07-21 10:47:48 EDT-------
changing componet

**Comment by cdeadmin** [comment]
------- Comment From rmatos@br.ibm.com 2017-07-24 08:14:10 EDT-------
Changed product and version

**Comment by ravanelli** [comment]
Test back

**Comment by cdeadmin** [comment]
Test mirroring a comment from GitHub to LTC ... exercising the new MirrorTool API method

**Comment by cdeadmin** [comment]
Test calling MirrorTool.disable_github_comments with action = create

**Comment by cdeadmin** [comment]
Test mirroring a comment from GitHub to LTC ... exercising the new MirrorTool API method

**Comment by cdeadmin** [comment]
Test calling MirrorTool.disable_github_comments with action = delete

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2018-04-23 14:23:15 EDT-------
Confirmed ... GitHub mirror track has appeared.
Test calling MirrorTool.disable_github_comments with action = create

**Comment by cdeadmin** [comment]
Testing the delete call again ....

**Comment by cdeadmin** [comment]
Test calling MirrorTool.disable_github_comments with action = delete

**Comment by cdeadmin** [comment]
Testing the delete call again ...
Testing the delete call again ...

**Comment by cdeadmin** [comment]
Performing another test of the delete call.

**Comment by cdeadmin** [comment]
Testing the delete call again ....
