### ISSUE TITLE
CCA: test mirroring block bug to GitHub

### ISSUE THREAD

**Issue by cdeadmin** [ravanelli/mirror_test#8]
<cde:info> Mirrored with LTC bug #147885 </cde:info>

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-21 14:44:15 EDT-------
---Problem Description---
Testing mirroring to GitHub.

Set this up as a block bug immediately to check labels.

**Comment by cdeadmin** [comment]
Good ... the BLOCKER label which was specifically configured for this repository was selected.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-21 14:48:07 EDT-------
Test setting bug status = NEEDINFO

**Comment by okc-ok** [comment]
This issue is taking on a '70s color theme with these labels ...

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-21 14:51:36 EDT-------
See what happens when the bug is REJECTED

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-21 14:52:43 EDT-------
... also test lowering the severity to 'low'

**Comment by okc-ok** [comment]
Checking the comment cutoff logic against GitHub.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-21 14:44:15 EDT-------
---Problem Description---
Testing mirroring to GitHub.

Set this up as a block bug immediately to check labels.
Good ... the BLOCKER label which was specifically configured for this repository was selected.

------- Comment From carndt@us.ibm.com 2017-07-21 14:48:07 EDT-------
Test setting bug status = NEEDINFO
This issue is taking on a '70s color theme with these labels ...
